version: "3.8"

services:
  kyoo:
    build: "."
    restart: on-failure
    environment:
      - Database__Server=postgres
    ports:
      - 80:5000
    depends_on:
      - postgres
    volumes:
      - kyoo:/var/lib/kyoo
  postgres:
    image: "postgres"
    restart: on-failure
    environment:
      - POSTGRES_USER=kyoo
      - POSTGRES_PASSWORD=kyooPassword
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  kyoo:
  db:
